import json
import re

# Read the testsData.ts
with open("src/data/testsData.ts", "r", encoding="utf-8") as f:
    content = f.read()

# Extract the JSON object using regex (simple approximation)
# Since it's a TS object, we might have to clean it up slightly, 
# but testsData.ts was generated by json.dumps so it's very close to valid JSON.
json_str = content.split("export const testsData: Record<number, TestData> = ")[1]
json_str = json_str.strip()
if json_str.endswith(";"):
    json_str = json_str[:-1]

data = json.loads(json_str)

# Build the answer key dictionary
answer_keys = {}
for grade_str, test in data.items():
    grade = str(test["grade"])
    answer_keys[grade] = {"russian": {}, "math": {}, "logic": {}}
    
    for q in test.get("russian", []):
        answer_keys[grade]["russian"][q["id"]] = {"ans": q["correctAnswer"].strip().lower(), "pts": q["points"]}
    for q in test.get("math", []):
        answer_keys[grade]["math"][q["id"]] = {"ans": q["correctAnswer"].strip().lower(), "pts": q["points"]}
    for q in test.get("logic", []):
        answer_keys[grade]["logic"][q["id"]] = {"ans": q["correctAnswer"].strip().lower(), "pts": q["points"]}

gas_code = """const SHEET_TESTS = "Результаты тестов";
const SHEET_CRM = "CRM Менеджеров";

const ANSWER_KEYS = """ + json.dumps(answer_keys, ensure_ascii=False, indent=2) + """;

function sanitize(input) {
  if (typeof input !== 'string') return input;
  // Prevent CSV injection
  let sanitized = input.replace(/[<>]/g, ''); // Strip obvious HTML tags
  if (/^[=+\-@]/.test(sanitized)) {
    sanitized = "'" + sanitized;
  }
  return sanitized;
}

function calculateScores(grade, answers) {
  const keys = ANSWER_KEYS[String(grade)];
  if (!keys) return { russian: 0, math: 0, logic: 0 };
  
  let ru = 0, ma = 0, lo = 0;
  
  if (answers && typeof answers === 'object') {
    Object.keys(keys.russian).forEach(qId => {
      if (answers[qId] && answers[qId].trim().toLowerCase() === keys.russian[qId].ans) ru += keys.russian[qId].pts;
    });
    Object.keys(keys.math).forEach(qId => {
      if (answers[qId] && answers[qId].trim().toLowerCase() === keys.math[qId].ans) ma += keys.math[qId].pts;
    });
    Object.keys(keys.logic).forEach(qId => {
      if (answers[qId] && answers[qId].trim().toLowerCase() === keys.logic[qId].ans) lo += keys.logic[qId].pts;
    });
  }
  return { russian: ru, math: ma, logic: lo };
}

function doPost(e) {
  const lock = LockService.getScriptLock();
  try {
    // Wait up to 5 seconds for other processes to finish.
    lock.waitLock(5000);
    
    const data = JSON.parse(e.postData.contents);
    const action = data.action;
    
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    let testSheet = ss.getSheetByName(SHEET_TESTS);
    let crmSheet = ss.getSheetByName(SHEET_CRM);
    
    if (testSheet.getLastRow() === 0) {
      testSheet.appendRow(["Дата", "ФИО Ученика", "Класс", "Русский язык", "Математика", "Логика", "Общий балл", "Уникальный ID теста", "Timestamp", "Читерство"]);
    }
    if (crmSheet.getLastRow() === 0) {
      crmSheet.appendRow(["Дата", "Менеджер", "ФИО Родителя", "Номер телефона", "ID Теста (ученика)", "Стадия работы", "Оплата до.инфо", "Взнос", "Общая стоимость", "Оплата -1-месяц"]);
    }

    if (action === "submitTest") {
      const { testId, studentName, grade, answers, cheated } = data;
      
      // Check if testId already exists to prevent duplicate submissions
      const dataRange = testSheet.getDataRange().getValues();
      for (let i = 1; i < dataRange.length; i++) {
        if (dataRange[i][7] === testId) {
          return ContentService.createTextOutput(JSON.stringify({ success: false, error: "Test already submitted" })).setMimeType(ContentService.MimeType.JSON);
        }
      }

      let scores = { russian: 0, math: 0, logic: 0 };
      if (!cheated) {
        scores = calculateScores(grade, answers);
      }
      const totalScore = scores.russian + scores.math + scores.logic;
      const safeName = sanitize(studentName || "Без имени");
      
      const ts = new Date().getTime();
      testSheet.appendRow([new Date(ts).toLocaleString("ru-RU", { timeZone: "Asia/Almaty" }), safeName, grade, scores.russian, scores.math, scores.logic, totalScore, testId, ts, cheated ? "ДА" : "НЕТ"]);
      
      return ContentService.createTextOutput(JSON.stringify({ success: true, totalScore, cheated: !!cheated })).setMimeType(ContentService.MimeType.JSON);
    }
    
    if (action === "submitManagerForm") {
      const { manager, parentName, phone, testId, stage, paymentPreInfo, deposit, totalCost, paymentMinus1Month } = data;
      
      // Validation 1: Does testId exist in tests sheet?
      const testData = testSheet.getDataRange().getValues();
      let testFound = false;
      let testTimestamp = 0;
      for (let i = 1; i < testData.length; i++) {
        if (testData[i][7] === testId) {
          testFound = true;
          testTimestamp = testData[i][8] || 0; // Timestamp column
          break;
        }
      }
      
      if (!testFound) {
        return ContentService.createTextOutput(JSON.stringify({ success: false, error: "Неверный QR-код. Тест не найден в базе данных." })).setMimeType(ContentService.MimeType.JSON);
      }
      
      // Validation 2: Is the test too old? (e.g., > 12 hours)
      const now = new Date().getTime();
      const MAX_AGE_MS = 12 * 60 * 60 * 1000;
      if (now - testTimestamp > MAX_AGE_MS) {
        return ContentService.createTextOutput(JSON.stringify({ success: false, error: "Срок действия QR-кода истек (прошло более 12 часов с момента сдачи теста)." })).setMimeType(ContentService.MimeType.JSON);
      }

      // Validation 3: Is it already in CRM?
      const crmData = crmSheet.getDataRange().getValues();
      for (let i = 1; i < crmData.length; i++) {
        if (crmData[i][4] === testId) {
          return ContentService.createTextOutput(JSON.stringify({ success: false, error: "Этот ученик уже зарегистрирован в CRM другим менеджером!" })).setMimeType(ContentService.MimeType.JSON);
        }
      }

      const safeManager = sanitize(manager);
      const safeParent = sanitize(parentName);
      const safePhone = sanitize(phone);
      
      crmSheet.appendRow([new Date().toLocaleString("ru-RU", { timeZone: "Asia/Almaty" }), safeManager, safeParent, safePhone, testId, stage, paymentPreInfo, deposit, totalCost, paymentMinus1Month]);
      return ContentService.createTextOutput(JSON.stringify({ success: true })).setMimeType(ContentService.MimeType.JSON);
    }
    
    return ContentService.createTextOutput(JSON.stringify({ success: false, error: "Unknown action" })).setMimeType(ContentService.MimeType.JSON);
  } catch (error) {
    return ContentService.createTextOutput(JSON.stringify({ success: false, error: error.message })).setMimeType(ContentService.MimeType.JSON);
  } finally {
    lock.releaseLock();
  }
}

function doOptions(e) {
  return ContentService.createTextOutput("").setMimeType(ContentService.MimeType.JSON).setHeaders({
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type"
  });
}
"""

with open("scratch/Code.gs", "w", encoding="utf-8") as f:
    f.write(gas_code)
